postgres:
  image: postgres:9.6.1
  environment:
    POSTGRES_PASSWORD: adminadmin
    POSTGRES_DB: workflow-db

imixssample:
  image: imixs/imixs-sample
  environment:
    WILDFLY_PASS: adminadmin
    DEBUG: "true"
  ports:
    - "8080:8080"
    - "9990:9990"
  links: 
    - postgres:postgres
 

    
 