version: "3.6"
services:

  imixssample-db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflow-db
  
  imixssample-app:
    image: imixs/imixs-jsf-example
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://imixssample-db/workflow-db"
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"
    volumes:
      - ~/git/imixs-jsf-example/src/docker/deployments:/opt/wildfly/standalone/deployments/    

  imixsadmin:
    image: imixs/imixs-admin
    ports:
      - "8888:8080"      
      
  mailgateway:
    image: imixs/exim4
    environment:
      EXIM_SMARTHOST: "www149.your-server.de:25"
      EXIM_PASSWORD: "www149.your-server.de:webmaster@imixs.com:webmaster4imixsmail"
      EXIM_ALLOWED_SENDERS: "10.0.0.0/8:172.16.0.0/12:192.168.0.0/16"  
      